drop table if exists phf_schedule;

create table phf_schedule (
    game_id int, 
    game_date date, 
    league varchar(8),
    league_id int, 
    season int,
    season_id int, 
    game_type varchar(3), 
    `status` varchar(25),
    winner varchar(50), 
    home_score int,
    home_team_id int, 
    home_team varchar(50), 
    away_score int, 
    away_team_id int, 
    away_team varchar(50), 
    overtime boolean, 
    shootout boolean, 
    attendance varchar(10),
    home_team_short varchar(6), 
    home_team_logo_url varchar(300), 
    home_division_id int,
    home_division varchar(25),
    away_team_short varchar(10), 
    away_team_logo_url varchar(6), 
    away_division_id int, 
    away_division varchar(25), 
    facility_id varchar(6), 
    facility varchar(100), 
    facility_address varchar(100), 
    rink_id varchar(50),
    rink varchar(50), 
    datetime_tz datetime, 
    time_zone_abbr varchar(6),
    updated_at datetime, 
    created_at datetime, 
    notes varchar(200),
    allow_players boolean, 
    tickets_url varchar(200), 
    watch_live_url varchar(200), 
    external_url varchar(200),
    has_play_by_play boolean, 
    `type` varchar(10),
    id varchar(8),
    PRIMARY KEY (game_id)
);