drop table if exists skater_stats;

create table skater_stats (
    player_name varchar(50),
    player_id float,
    jersey int,
    team varchar(100),
    position varchar(6),
    season int,
    season_id int,
    season_type varchar(50),
    league varchar(8),
    league_id int,
    division_id int,
    games_played int,
    goals int,
    assists int,
    points int,
    points_per_game float,
    shots int,
    shots_blocked int,
    shots_on_goal int,
    shot_pct float,
    power_play_goal float,
    short_hand_goal float,
    game_winning_goal int,
    plus_minus int,
    faceoff_record varchar(12),
    faceoff_win_pct float,
    faceoff_won int,
    faceoff_lost int,
    blocks int,
    penalty_minutes int,
    takeaways int,
    giveaway int
);